//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluidBar.Localization {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FluidBar.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 已复制 的本地化字符串。
        /// </summary>
        public static string Clipboard_Copied {
            get {
                return ResourceManager.GetString("Clipboard_Copied", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 剪贴板 的本地化字符串。
        /// </summary>
        public static string Clipboard_Name {
            get {
                return ResourceManager.GetString("Clipboard_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 复制文本时在灵动岛上显示内容 的本地化字符串。
        /// </summary>
        public static string Clipboard_Description {
            get {
                return ResourceManager.GetString("Clipboard_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 音量 的本地化字符串。
        /// </summary>
        public static string Volume_Name {
            get {
                return ResourceManager.GetString("Volume_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 音量调节 的本地化字符串。
        /// </summary>
        public static string Volume_Adjusting {
            get {
                return ResourceManager.GetString("Volume_Adjusting", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 电池 的本地化字符串。
        /// </summary>
        public static string Battery_Name {
            get {
                return ResourceManager.GetString("Battery_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 充电中 的本地化字符串。
        /// </summary>
        public static string Battery_Charging {
            get {
                return ResourceManager.GetString("Battery_Charging", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 电量低 的本地化字符串。
        /// </summary>
        public static string Battery_Low {
            get {
                return ResourceManager.GetString("Battery_Low", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 CPU 的本地化字符串。
        /// </summary>
        public static string CPU_Name {
            get {
                return ResourceManager.GetString("CPU_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 CPU 占用 的本地化字符串。
        /// </summary>
        public static string CPU_Usage {
            get {
                return ResourceManager.GetString("CPU_Usage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 系统负载较高 的本地化字符串。
        /// </summary>
        public static string CPU_HighLoad {
            get {
                return ResourceManager.GetString("CPU_HighLoad", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 内存 的本地化字符串。
        /// </summary>
        public static string Memory_Name {
            get {
                return ResourceManager.GetString("Memory_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 内存占用 的本地化字符串。
        /// </summary>
        public static string Memory_Usage {
            get {
                return ResourceManager.GetString("Memory_Usage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 内存不足，建议关闭应用 的本地化字符串。
        /// </summary>
        public static string Memory_LowWarning {
            get {
                return ResourceManager.GetString("Memory_LowWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 磁盘 的本地化字符串。
        /// </summary>
        public static string Disk_Name {
            get {
                return ResourceManager.GetString("Disk_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 磁盘繁忙 的本地化字符串。
        /// </summary>
        public static string Disk_Busy {
            get {
                return ResourceManager.GetString("Disk_Busy", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 磁盘活动 的本地化字符串。
        /// </summary>
        public static string Disk_Active {
            get {
                return ResourceManager.GetString("Disk_Active", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 网络 的本地化字符串。
        /// </summary>
        public static string Network_Name {
            get {
                return ResourceManager.GetString("Network_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 网络已断开 的本地化字符串。
        /// </summary>
        public static string Network_Disconnected {
            get {
                return ResourceManager.GetString("Network_Disconnected", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 网络已连接 的本地化字符串。
        /// </summary>
        public static string Network_Connected {
            get {
                return ResourceManager.GetString("Network_Connected", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 天气 的本地化字符串。
        /// </summary>
        public static string Weather_Name {
            get {
                return ResourceManager.GetString("Weather_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 媒体播放 的本地化字符串。
        /// </summary>
        public static string Media_Name {
            get {
                return ResourceManager.GetString("Media_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 显示当前媒体来源、曲目、播放状态 的本地化字符串。
        /// </summary>
        public static string Media_Description {
            get {
                return ResourceManager.GetString("Media_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Agent 状态 的本地化字符串。
        /// </summary>
        public static string Agent_Name {
            get {
                return ResourceManager.GetString("Agent_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 监听 Claude Code / Codex 本地 hook 事件 的本地化字符串。
        /// </summary>
        public static string Agent_Description {
            get {
                return ResourceManager.GetString("Agent_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 任务完成 的本地化字符串。
        /// </summary>
        public static string Agent_TaskCompleted {
            get {
                return ResourceManager.GetString("Agent_TaskCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 构建成功 的本地化字符串。
        /// </summary>
        public static string Agent_BuildSuccess {
            get {
                return ResourceManager.GetString("Agent_BuildSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 构建失败 的本地化字符串。
        /// </summary>
        public static string Agent_BuildFailed {
            get {
                return ResourceManager.GetString("Agent_BuildFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 测试完成 的本地化字符串。
        /// </summary>
        public static string Agent_TestCompleted {
            get {
                return ResourceManager.GetString("Agent_TestCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Git 状态 的本地化字符串。
        /// </summary>
        public static string Agent_GitStatus {
            get {
                return ResourceManager.GetString("Agent_GitStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 通知 的本地化字符串。
        /// </summary>
        public static string Notification_Name {
            get {
                return ResourceManager.GetString("Notification_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Windows 通知 的本地化字符串。
        /// </summary>
        public static string Notification_Description {
            get {
                return ResourceManager.GetString("Notification_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string Tray_Exit {
            get {
                return ResourceManager.GetString("Tray_Exit", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 纯音乐，请欣赏 的本地化字符串。
        /// </summary>
        public static string Lyrics_Instrumental {
            get {
                return ResourceManager.GetString("Lyrics_Instrumental", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 系统 的本地化字符串。
        /// </summary>
        public static string System_Name {
            get {
                return ResourceManager.GetString("System_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 主题变更 的本地化字符串。
        /// </summary>
        public static string System_ThemeChanged {
            get {
                return ResourceManager.GetString("System_ThemeChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 运行正常 的本地化字符串。
        /// </summary>
        public static string Status_Normal {
            get {
                return ResourceManager.GetString("Status_Normal", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 灵动岛 的本地化字符串。
        /// </summary>
        public static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
    }
}
